// <auto-generated />
using Demo.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Demo.Server.Migrations
{
    [DbContext(typeof(SampleDbContext))]
    [Migration("20250511170624_sqlite_migration_581")]
    partial class sqlite_migration_581
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("Demo.Server.Data.City", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Elevation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("City", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Country = "Greece",
                            Elevation = 70,
                            Name = "Athens"
                        },
                        new
                        {
                            Id = 2L,
                            Country = "Spain",
                            Elevation = 0,
                            Name = "Barcelona"
                        },
                        new
                        {
                            Id = 3L,
                            Country = "China",
                            Elevation = 43,
                            Name = "Beijing"
                        },
                        new
                        {
                            Id = 4L,
                            Country = "Serbia",
                            Elevation = 117,
                            Name = "Belgrade"
                        },
                        new
                        {
                            Id = 5L,
                            Country = "Brazil",
                            Elevation = 1172,
                            Name = "Brasília"
                        },
                        new
                        {
                            Id = 6L,
                            Country = "Slovakia",
                            Elevation = 124,
                            Name = "Bratislava"
                        },
                        new
                        {
                            Id = 7L,
                            Country = "Romania",
                            Elevation = 85,
                            Name = "Bucharest"
                        },
                        new
                        {
                            Id = 8L,
                            Country = "Argentina",
                            Elevation = 25,
                            Name = "Buenos Aires"
                        },
                        new
                        {
                            Id = 9L,
                            Country = "Mexico",
                            Elevation = 1140,
                            Name = "Ciudad Juárez"
                        },
                        new
                        {
                            Id = 10L,
                            Country = "Romania",
                            Elevation = 360,
                            Name = "Cluj-Napoca"
                        },
                        new
                        {
                            Id = 11L,
                            Country = "Argentina",
                            Elevation = 352,
                            Name = "Córdoba"
                        },
                        new
                        {
                            Id = 12L,
                            Country = "Slovakia",
                            Elevation = 206,
                            Name = "Košice"
                        },
                        new
                        {
                            Id = 13L,
                            Country = "Spain",
                            Elevation = 650,
                            Name = "Madrid"
                        },
                        new
                        {
                            Id = 14L,
                            Country = "Mexico",
                            Elevation = 2240,
                            Name = "Mexico City"
                        },
                        new
                        {
                            Id = 15L,
                            Country = "Russia",
                            Elevation = 156,
                            Name = "Moscow"
                        },
                        new
                        {
                            Id = 16L,
                            Country = "Serbia",
                            Elevation = 195,
                            Name = "Niš"
                        },
                        new
                        {
                            Id = 17L,
                            Country = "Serbia",
                            Elevation = 80,
                            Name = "Novi Sad"
                        },
                        new
                        {
                            Id = 18L,
                            Country = "Greece",
                            Elevation = 0,
                            Name = "Patras"
                        },
                        new
                        {
                            Id = 19L,
                            Country = "Serbia",
                            Elevation = 450,
                            Name = "Prizren"
                        },
                        new
                        {
                            Id = 20L,
                            Country = "Brazil",
                            Elevation = 0,
                            Name = "Rio de Janeiro"
                        },
                        new
                        {
                            Id = 21L,
                            Country = "Argentina",
                            Elevation = 31,
                            Name = "Rosario"
                        },
                        new
                        {
                            Id = 22L,
                            Country = "Russia",
                            Elevation = 0,
                            Name = "Saint Petersburg"
                        },
                        new
                        {
                            Id = 23L,
                            Country = "Brazil",
                            Elevation = 760,
                            Name = "São Paulo"
                        },
                        new
                        {
                            Id = 24L,
                            Country = "China",
                            Elevation = 0,
                            Name = "Shanghai"
                        },
                        new
                        {
                            Id = 25L,
                            Country = "Greece",
                            Elevation = 0,
                            Name = "Thessaloniki"
                        },
                        new
                        {
                            Id = 26L,
                            Country = "Mexico",
                            Elevation = 20,
                            Name = "Tijuana"
                        },
                        new
                        {
                            Id = 27L,
                            Country = "Romania",
                            Elevation = 90,
                            Name = "Timișoara"
                        },
                        new
                        {
                            Id = 28L,
                            Country = "Spain",
                            Elevation = 0,
                            Name = "Valencia"
                        },
                        new
                        {
                            Id = 29L,
                            Country = "Russia",
                            Elevation = 0,
                            Name = "Vladivostok"
                        },
                        new
                        {
                            Id = 30L,
                            Country = "China",
                            Elevation = 405,
                            Name = "Xi'an"
                        },
                        new
                        {
                            Id = 31L,
                            Country = "Slovakia",
                            Elevation = 378,
                            Name = "Žilina"
                        });
                });

            modelBuilder.Entity("Demo.Server.Data.Query", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<string>("Sql")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Query", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Sql = "SELECT ID, Name, Country, Elevation FROM City"
                        },
                        new
                        {
                            Id = 2L,
                            Sql = "SELECT ID, Name, Country, Elevation FROM City WHERE Elevation > {0}"
                        },
                        new
                        {
                            Id = 3L,
                            Sql = "SELECT ID, Name, Country, Elevation FROM City WHERE Elevation BETWEEN {0} AND {1}"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
